CREATE TABLE payout (
    id INTEGER PRIMARY KEY,
    createdAt INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
    succeeded BOOLEAN DEFAULT FALSE
);

CREATE TABLE share (
    id INTEGER PRIMARY KEY,
    publicAddress TEXT NOT NULL,
    createdAt INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
    payoutId INTEGER,
    CONSTRAINT share_fk_payout_id FOREIGN KEY (payoutId) REFERENCES payout (id)
);