name: 'Assert JSON output'
author: 'EnricoMi'
description: 'A GitHub Action that asserts the publish action''s JSON output'

inputs:
  json:
    description: 'JSON content to assess.'
    required: true
  json_file:
    description: 'Path to the JSON file to assess.'
    required: true

runs:
  using: 'composite'
  steps:
  - name: JSON file
    shell: bash
    run: |
      jq '.cases' "${{ inputs.json_file }}"

  - name: JSON output
    if: always()
    env:
      SUMMARY: ${{ fromJSON( inputs.json ).summary }}
    shell: bash
    run: |
      echo "summary=$SUMMARY"

branding:
  icon: 'check-circle'
  color: 'green'