/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface PublicPackage {
  identity: string
  frostPackage: string
  groupSecretKeyShardEncrypted: string
  checksum: string
}
export declare function deserializePublicPackage(round1PublicPackage: string): PublicPackage
export interface Round2PublicPackage {
  senderIdentity: string
  recipientIdentity: string
  frostPackage: string
  checksum: string
}
export interface Round2CombinedPublicPackage {
  packages: Array<Round2PublicPackage>
}
export declare function deserializeRound2CombinedPublicPackage(round2CombinedPublicPackage: string): Round2CombinedPublicPackage
export const KEY_LENGTH: number
export const NONCE_LENGTH: number
export declare function randomBytes(bytesLength: number): Uint8Array
export interface BoxedMessage {
  nonce: string
  boxedMessage: string
}
export declare function boxMessage(plaintext: string, senderSecretKey: Uint8Array, recipientPublicKey: string): BoxedMessage
export declare function unboxMessage(boxedMessage: string, nonce: string, senderPublicKey: string, recipientSecretKey: Uint8Array): string
export declare function initSignalHandler(): void
export const ASSET_ID_LENGTH: number
export const ASSET_METADATA_LENGTH: number
export const ASSET_NAME_LENGTH: number
export const ASSET_LENGTH: number
export const NOTE_ENCRYPTION_KEY_LENGTH: number
export const MAC_LENGTH: number
export const ENCRYPTED_NOTE_PLAINTEXT_LENGTH: number
export const ENCRYPTED_NOTE_LENGTH: number
export const PUBLIC_ADDRESS_LENGTH: number
export const RANDOMNESS_LENGTH: number
export const MEMO_LENGTH: number
export const AMOUNT_VALUE_LENGTH: number
export const DECRYPTED_NOTE_LENGTH: number
export interface NativeSpendDescription {
  treeSize: number
  rootHash: Buffer
  nullifier: Buffer
}
export const PROOF_LENGTH: number
export const TRANSACTION_SIGNATURE_LENGTH: number
export const TRANSACTION_PUBLIC_KEY_RANDOMNESS_LENGTH: number
export const TRANSACTION_EXPIRATION_LENGTH: number
export const TRANSACTION_FEE_LENGTH: number
export const LATEST_TRANSACTION_VERSION: number
export declare function verifyTransactions(serializedTransactions: Array<Buffer>): boolean
export const enum LanguageCode {
  English = 0,
  ChineseSimplified = 1,
  ChineseTraditional = 2,
  French = 3,
  Italian = 4,
  Japanese = 5,
  Korean = 6,
  Spanish = 7
}
export interface Key {
  spendingKey: string
  viewKey: string
  incomingViewKey: string
  outgoingViewKey: string
  publicAddress: string
  proofAuthorizingKey: string
}
export declare function generateKey(): Key
export declare function spendingKeyToWords(privateKey: string, languageCode: LanguageCode): string
export declare function wordsToSpendingKey(words: string, languageCode: LanguageCode): string
export declare function generatePublicAddressFromIncomingViewKey(ivkString: string): string
export declare function generateKeyFromPrivateKey(privateKey: string): Key
export declare function initializeSapling(): void
export declare function isValidPublicAddress(hexAddress: string): boolean
/**
 * Return the number of processing units available to the system and to the current process.
 *
 * Note that the numbers returned by this method may change during the lifetime of the process.
 * Examples of events that may cause the numbers to change:
 * - enabling/disabling Simultaneous Multi-Threading (SMT)
 * - enabling/disabling individual CPU threads or CPU cores
 * - on Linux, changing CPU affinity masks for the process
 * - on Linux, changing cgroup quotas for the process
 *
 * Also note that these numbers may not be accurate when running in a virtual machine or in a
 * sandboxed environment.
 */
export declare function getCpuCount(): CpuCount
export declare function generateRandomizedPublicKey(viewKeyString: string, publicKeyRandomnessString: string): string
export class FishHashContext {
  constructor(full: boolean)
  prebuildDataset(threads: number): void
  hash(header: Buffer): Buffer
}
export class BoxKeyPair {
  constructor()
  static fromHex(secretHex: string): BoxKeyPair
  get publicKey(): Buffer
  get secretKey(): Buffer
}
export type NativeRollingFilter = RollingFilter
export class RollingFilter {
  constructor(items: number, rate: number)
  add(value: Buffer): void
  test(value: Buffer): boolean
}
export type NativeAsset = Asset
export class Asset {
  constructor(creatorPublicAddress: string, name: string, metadata: string)
  metadata(): Buffer
  name(): Buffer
  nonce(): number
  creator(): Buffer
  static nativeId(): Buffer
  id(): Buffer
  serialize(): Buffer
  static deserialize(jsBytes: Buffer, skipValidation?: boolean | undefined | null): NativeAsset
}
export type NativeNoteEncrypted = NoteEncrypted
export class NoteEncrypted {
  constructor(jsBytes: Buffer, skipValidation?: boolean | undefined | null)
  serialize(): Buffer
  equals(other: NoteEncrypted): boolean
  /**
   * The commitment hash of the note
   * This hash is what gets used for the leaf nodes in a Merkle Tree.
   */
  hash(): Buffer
  /**
   * Hash two child hashes together to calculate the hash of the
   * new parent
   */
  static combineHash(depth: number, jsLeft: Buffer, jsRight: Buffer): Buffer
  /** Returns undefined if the note was unable to be decrypted with the given key. */
  decryptNoteForOwner(incomingViewKey: Buffer): Buffer | null
  decryptNoteForOwners(incomingViewKeys: Array<Buffer>): Array<Buffer | undefined | null>
  /** Returns undefined if the note was unable to be decrypted with the given key. */
  decryptNoteForSpender(outgoingViewKey: Buffer): Buffer | null
}
export type NativeNote = Note
export class Note {
  constructor(owner: string, value: bigint, memo: Buffer, assetId: Buffer, sender: string)
  static deserialize(jsBytes: Buffer): NativeNote
  serialize(): Buffer
  /**
   * The commitment hash of the note
   * This hash is what gets used for the leaf nodes in a Merkle Tree.
   */
  hash(): Buffer
  /** Value this note represents. */
  value(): bigint
  /**
   * Arbitrary note the spender can supply when constructing a spend so the
   * receiver has some record from whence it came.
   * Note: While this is encrypted with the output, it is not encoded into
   * the proof in any way.
   */
  memo(): string
  /** Asset identifier associated with this note */
  assetId(): Buffer
  /** Sender of the note */
  sender(): string
  /** Owner of the note */
  owner(): string
  /**
   * Compute the nullifier for this note, given the private key of its owner.
   *
   * The nullifier is a series of bytes that is published by the note owner
   * only at the time the note is spent. This key is collected in a massive
   * 'nullifier set', preventing double-spend.
   */
  nullifier(ownerViewKey: string, position: bigint): Buffer
}
export type NativeTransactionPosted = TransactionPosted
export class TransactionPosted {
  constructor(jsBytes: Buffer)
  serialize(): Buffer
  notesLength(): number
  getNote(index: number): Buffer
  spendsLength(): number
  getSpend(index: number): NativeSpendDescription
  fee(): bigint
  transactionSignature(): Buffer
  hash(): Buffer
  expiration(): number
}
export type NativeTransaction = Transaction
export class Transaction {
  constructor(version: number)
  /** Create a proof of a new note owned by the recipient in this transaction. */
  output(note: Note): void
  /** Spend the note owned by spender_hex_key at the given witness location. */
  spend(note: Note, witness: object): void
  /** Mint a new asset with a given value as part of this transaction. */
  mint(asset: Asset, value: bigint, transferOwnershipTo?: string | undefined | null): void
  /** Burn some supply of a given asset and value as part of this transaction. */
  burn(assetIdJsBytes: Buffer, value: bigint): void
  /**
   * Special case for posting a miners fee transaction. Miner fee transactions
   * are unique in that they generate currency. They do not have any spends
   * or change and therefore have a negative transaction fee. In normal use,
   * a miner would not accept such a transaction unless it was explicitly set
   * as the miners fee.
   */
  post_miners_fee(spenderHexKey: string): Buffer
  /**
   * Used to generate invalid miners fee transactions for testing. Call
   * post_miners_fee instead in user-facing code.
   */
  _postMinersFeeUnchecked(spenderHexKey: string): Buffer
  /**
   * Post the transaction. This performs a bit of validation, and signs
   * the spends with a signature that proves the spends are part of this
   * transaction.
   *
   * Transaction fee is the amount the spender wants to send to the miner
   * for mining this transaction. This has to be non-negative; sane miners
   * wouldn't accept a transaction that takes money away from them.
   *
   * sum(spends) - sum(outputs) - intended_transaction_fee - change = 0
   * aka: self.value_balance - intended_transaction_fee - change = 0
   */
  post(spenderHexKey: string, changeGoesTo: string | undefined | null, intendedTransactionFee: bigint): Buffer
  build(proofAuthorizingKeyStr: string, viewKeyStr: string, outgoingViewKeyStr: string, intendedTransactionFee: bigint, changeGoesTo?: string | undefined | null): Buffer
  setExpiration(sequence: number): void
}
export type NativeUnsignedTransaction = UnsignedTransaction
export class UnsignedTransaction {
  constructor(jsBytes: Buffer)
  serialize(): Buffer
  randomizedPublicKey(): string
  publicKeyRandomness(): string
  hash(): Buffer
  signingPackage(nativeIdentiferCommitments: Array<string>): string
  sign(spenderHexKey: string): Buffer
  addSignature(signature: Buffer): Buffer
}
export class FoundBlockResult {
  randomness: string
  miningRequestId: number
  constructor(randomness: string, miningRequestId: number)
}
export class ThreadPoolHandler {
  constructor(threadCount: number, batchSize: number, pauseOnSuccess: boolean, useFishHash: boolean, fishHashFullContext: boolean)
  newWork(headerBytes: Buffer, target: Buffer, miningRequestId: number, fishHash: boolean, xnLength: number): void
  stop(): void
  pause(): void
  getFoundBlock(): FoundBlockResult | null
  getHashRateSubmission(): number
}
export class CpuCount {
  /**
   * Estimate of the number of threads that can run simultaneously on the system. This is
   * usually the same as `logical_count`, but on some systems (e.g. Linux), users can set limits
   * on individual processes, and so `available_parallelism` may sometimes be lower than
   * `logical_count`.
   */
  availableParallelism: number
  /**
   * Total number of 'logical CPUs', or 'virtual CPUs' or 'CPU threads' available on the system.
   * This number differs from `physical_count` on systems that have Simultaneous Multi-Threading
   * (SMT) enabled; on systems that do not have SMT enabled, `logical_count` and
   * `physical_count` should be the same number.
   *
   * Note, on some systems and configurations, not all logical CPUs may be available to the
   * current process, see `available_parallelism`.
   */
  logicalCount: number
  /**
   * Total number of CPU cores available on the system.
   *
   * Note, on some systems and configurations, not all physical CPUs may be available to the
   * current process, see `available_parallelism`.
   */
  physicalCount: number
}
export namespace multisig {
  export const IDENTITY_LEN: number
  export const SECRET_LEN: number
  export function createSigningCommitment(secret: string, keyPackage: string, transactionHash: Buffer, signers: Array<string>): string
  export function createSignatureShare(secret: string, keyPackage: string, signingPackage: string): string
  export function generateAndSplitKey(minSigners: number, identities: Array<string>): TrustedDealerKeyPackages
  export interface ParticipantKeyPackage {
    identity: string
    keyPackage: string
  }
  export interface TrustedDealerKeyPackages {
    publicAddress: string
    publicKeyPackage: string
    viewKey: string
    incomingViewKey: string
    outgoingViewKey: string
    proofAuthorizingKey: string
    keyPackages: Array<ParticipantKeyPackage>
  }
  export function dkgRound1(selfIdentity: string, minSigners: number, participantIdentities: Array<string>): DkgRound1Packages
  export interface DkgRound1Packages {
    round1SecretPackage: string
    round1PublicPackage: string
  }
  export function dkgRound2(secret: string, round1SecretPackage: string, round1PublicPackages: Array<string>): DkgRound2Packages
  export interface DkgRound2Packages {
    round2SecretPackage: string
    round2PublicPackage: string
  }
  export function dkgRound3(secret: ParticipantSecret, round2SecretPackage: string, round1PublicPackages: Array<string>, round2PublicPackages: Array<string>): DkgRound3Packages
  export interface DkgRound3Packages {
    publicAddress: string
    keyPackage: string
    publicKeyPackage: string
    viewKey: string
    incomingViewKey: string
    outgoingViewKey: string
    proofAuthorizingKey: string
  }
  export function aggregateSignatureShares(publicKeyPackageStr: string, signingPackageStr: string, signatureSharesArr: Array<string>): Buffer
  export type NativeSignatureShare = SignatureShare
    export class SignatureShare {
    constructor(jsBytes: Buffer)
    static fromFrost(frostSignatureShare: Buffer, identity: Buffer): NativeSignatureShare
    identity(): Buffer
    frostSignatureShare(): Buffer
    serialize(): Buffer
  }
  export class ParticipantSecret {
    constructor(jsBytes: Buffer)
    serialize(): Buffer
    static random(): ParticipantSecret
    toIdentity(): ParticipantIdentity
    decryptData(jsBytes: Buffer): Buffer
    decryptLegacyData(jsBytes: Buffer): Buffer
  }
  export class ParticipantIdentity {
    constructor(jsBytes: Buffer)
    serialize(): Buffer
    encryptData(jsBytes: Buffer): Buffer
  }
  export type NativePublicKeyPackage = PublicKeyPackage
    export class PublicKeyPackage {
    constructor(value: string)
    static fromFrost(frostPublicKeyPackage: Buffer, identities: Array<string>, minSigners: number): NativePublicKeyPackage
    serialize(): Buffer
    identities(): Array<Buffer>
    frostPublicKeyPackage(): Buffer
    minSigners(): number
  }
  export type NativeSigningCommitment = SigningCommitment
    export class SigningCommitment {
    constructor(jsBytes: Buffer)
    static fromRaw(identity: string, rawCommitments: Buffer, transactionHash: Buffer, signers: Array<string>): NativeSigningCommitment
    serialize(): Buffer
    identity(): Buffer
    rawCommitments(): Buffer
    verifyChecksum(transactionHash: Buffer, signerIdentities: Array<string>): boolean
  }
  export type NativeSigningPackage = SigningPackage
    export class SigningPackage {
    constructor(jsBytes: Buffer)
    unsignedTransaction(): NativeUnsignedTransaction
    signers(): Array<Buffer>
    frostSigningPackage(): Buffer
  }
}
export namespace xchacha20poly1305 {
  export const XKEY_LENGTH: number
  export const XSALT_LENGTH: number
  export const XNONCE_LENGTH: number
  export type NativeXChaCha20Poly1305Key = XChaCha20Poly1305Key
    export class XChaCha20Poly1305Key {
    constructor(passphrase: string)
    static fromParts(passphrase: string, salt: Buffer, nonce: Buffer): XChaCha20Poly1305Key
    deriveKey(salt: Buffer, nonce: Buffer): XChaCha20Poly1305Key
    deriveNewKey(): XChaCha20Poly1305Key
    static deserialize(jsBytes: Buffer): NativeXChaCha20Poly1305Key
    destroy(): void
    salt(): Buffer
    nonce(): Buffer
    key(): Buffer
    encrypt(plaintext: Buffer): Buffer
    decrypt(ciphertext: Buffer): Buffer
  }
}
