[package]
name = "ironfish_wasm"
version = "0.1.0"
authors = ["Iron Fish <contact@ironfish.network> (https://ironfish.network)"]
edition = "2018"
license = "MPL-2.0"

[dev-dependencies]
zcash_primitives = {git = "https://github.com/iron-fish/librustzcash.git", rev = "8186d84"}
pairing = { git = "https://github.com/iron-fish/librustzcash.git", rev = "8186d84", version = "0.16", features = ["expose-arith"]}
rand = {version = "0.7", features = ["wasm-bindgen"]}

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ironfish_rust= { path = "../ironfish-rust", features = ["wasm"] }
js-sys = "0.3.48"
wasm-bindgen = "0.2.71"

[profile.release]
opt-level = 3
lto = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O4", "-g", "--enable-mutable-globals"]

[lib]
crate-type = ["cdylib", "rlib"]