name: Bug Report
description: File a bug report
title: "[issue name]"
labels: ["bug", "triage"]
assignees:
  - iron-fish/engineering
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        If you are experiencing an issue after upgrading to a new version, please make sure you restart your Iron Fish node. You can check this by running `ironfish status` and `ironfish debug` and comparing the Iron Fish version. In both commands, the version should match.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: ex. v0.0.0
  - type: textarea
    id: debug
    attributes:
      label: Debug output
      description: Please copy and paste the output of `ironfish debug` / `yarn start debug` (same as you run any other `ironfish` commands).  This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output, like the command you entered and the logs leading up to the error. This will be automatically formatted into code, so no need for backticks.
      render: shell
