blank_issues_enabled: false
contact_links:
  - name: Github Discussions
    url: https://github.com/iron-fish/ironfish/discussions
    about: Ask and answer development questions here.
  - name: Discord
    url: https://discord.com/channels/771503434028941353/
    about: Learn more about the project and meet our community.
