services:
  fish:
    image: 'ironfish:latest'
    command: ['start', '--rpc.ipc', '--rpc.tcp', '--networkId=2', '--bootstrap=fish_bootstrap', '--forceMining']
    networks:
      - fish_tank
  fish_bootstrap:
    image: 'ironfish:latest'
    command: ['start', '--rpc.ipc', '--rpc.tcp', '--networkId=2']
    networks:
      - fish_tank

networks:
  fish_tank:
    driver: bridge
    internal: true
