[package]
name = "ironfish-phase2"
version = "0.2.2"
authors = ["Sean Bowe <ewillbefull@gmail.com>", "Iron Fish <contact@ironfish.network> (https://ironfish.network)"]
description = "Library for performing MPCs for creating zk-SNARK public parameters"
homepage = "https://github.com/iron-fish/ironfish"
license = "MIT OR Apache-2.0"
repository = "https://github.com/iron-fish/ironfish"

publish = false

[package.edition]
workspace = true

[dependencies]
pairing = "0.22.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
rayon = "1.6.1"
bellman = "0.13.1"
bls12_381 = "0.7.0"
ff = "0.12.0"
group = "0.12.0"
byteorder = "1"
blake2 = "0.10.6"
