version: "2.4"

services:
    node:
        image: ghcr.io/iron-fish/ironfish:latest
        volumes:
            - ~/.ironfish:/root/.ironfish
        tty: true
        restart: always
        command: ["start", "--graffiti", "graffitiExample", "--name", "nodeExample"]
        user: 1000:1000
        security_opt:
        - no-new-privileges:true

    miner:
        image: ghcr.io/iron-fish/ironfish:latest
        volumes:
            - ~/.ironfish:/root/.ironfish
        tty: true
        mem_limit: 8192M
        restart: always
        command: miners:start --threads -1
        user: 1000:1000
        security_opt:
        - no-new-privileges:true

networks:
    default:
